server:
  port: 9005
spring:
  application:
    name: loans 
# H2 Database connection properties
  datasource:
    url: jdbc:h2:mem:loansdb
    username: admin
    password: admin
# Hibernate/ JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
# Enabling H2 console property
  h2:
    console:
      enabled: true
  
 # Actuators Properties
 # Enabling all Actuator endpointsmanagement:
management:
  endpoints:
    web:
      exposure:
        include: '*'
#Distributed Tracing with ZIPKIN(management.zipkin.tracing.endpoints)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
# To enable info we have to write the property explicitly
  info:
    env:
      enabled: true
# http://localhost:9003/actuator/info: we will not get any data, now we need to provide data for our application as information
info:
 app:
  varsion: 0.0.1
  description: Loans Microservice
 contact: 7777777777
# Eureka Client Enabling Properties
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9002/eureka/
#(Eureka) This below property for Cloud only, communication will happen internally
  instance:
    prefer-ip-address: true
#Logging Pattern for Distributed tracing(Micrometer Tracing)
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  file:
    name: C:/logs/loans.log